name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - uses: actions/checkout@v1
    - name: Run Tests
      run: xcodebuild test -scheme Asterism-OSX
